### ISSUE TITLE
Should we default to 'UXA' with intel driver configurations?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/mhwd-db#3]
Hi team,

cos of current issues with Plasma5 it is better to default back to 'UXA' for all intel driver configurations:

* [xf86-video-intel](https://github.com/manjaro/mhwd-db/blob/master/pci/graphic_drivers/xf86-video-intel/MHWDCONFIG)
* [hybrid-intel-ati-bumblebee](https://github.com/manjaro/mhwd-db/blob/master/pci/graphic_drivers/hybrid-intel-ati-bumblebee/MHWDCONFIG)
* [hybrid-intel-nouveau-bumblebee](https://github.com/manjaro/mhwd-db/blob/master/pci/graphic_drivers/hybrid-intel-nouveau-bumblebee/MHWDCONFIG)
* [hybrid-intel-nvidia-340xx-bumblebee](https://github.com/manjaro/mhwd-db/blob/master/pci/graphic_drivers/hybrid-intel-nvidia-340xx-bumblebee/MHWDCONFIG)
* [hybrid-intel-nvidia-bumblebee](https://github.com/manjaro/mhwd-db/blob/master/pci/graphic_drivers/hybrid-intel-nvidia-bumblebee/MHWDCONFIG)

What do you think? Se also [phoronix](http://www.phoronix.com/scan.php?page=news_item&px=intel-plasma-5-driver-crash) and [kde packager list](https://mail.kde.org/pipermail/kde-distro-packagers/2015-August/000088.html).

**Comment by Ste74** [comment]
Hi Philip , before reading this solution proposed to fademind in our forum my notebook crash randomly , now for the last 3 weeks works fine . My gpu is hybrid ATI/Intel .. so for me I should go back

**Comment by philmmanjaro** [comment]
Yep, I suggested it a while ago. 'SNA' is faster but has currently some issues with plasma5. 'UXA' is the way to go until Intel has it fixed. If the other developers agree, we will default back to 'UXA' for now.

**Comment by Esclapion** [comment]
Less problems with UXA, it seems.

**Comment by AJSlye** [comment]
Yes, there are less issues using uxa, however the intel-tbb update in testing seems to have fixed the crashes (for me at least) with Plasma5.

**Comment by philmmanjaro** [comment]
What do you mean by **intel-tbb update**? However, **mhwd 0.5.6** will default now to 'UAX'.

**Comment by AJSlye** [comment]
An updated intel-tbb package was part of the testing updates a couple of
days ago.

**Comment by FadeMind** [comment]
UXA is half solution for this. Some new Intel geneations (broadwell, haswell) have sersious laggy performance under UXA. Older devices (sandy/ivy) don't have very poor performance with UXA.
IMO is better adding proper option to Manjaro Settings Manager with checkbox for Enable UXA on Intel.
Forcing UXA for ALL (with other DE too) is bad idea. Better is give an option with "One Click Checkbox" in MSM setup.

**Comment by philmmanjaro** [comment]
Well, we will consider this for sure. Atm it is 'UXA' for all. You can still edit it by changing it back within your **/etc/X11/mhwd.d/intel.conf** file.

**Comment by FadeMind** [comment]
Well, but information about using UXA as default should be placed where... Not everyone is geek ;)

**Comment by AJSlye** [comment]
The Intel graphics stack issue has been reported about more than just
Plasma 5.
There are other 3D based applications are having the same issues.

**Comment by Kirek** [comment]
We switched back to sna, closing this old question.
