### ISSUE TITLE
Consider reverting commit 71f5b5590dcfae4ce75cc8f4b75724a9b02dcdfa

### ISSUE THREAD

**Issue by PhoronixSucks** [manjaro/mhwd-db#4]
This method while it removes screen tearing with select Nvidia graphics cards does have obvious drawbacks that come with it like poor performance in some games (Specifically Wine games as they stutter heavily with it enabled verses it being disabled) and input lag as should be expected considering that it is main purpose is to be used as a workaround in case there is no compositing manager available to do the job.I think a better solution should be to just take the compiz-manjaro package created by korrode and using that by default as the compositing window manager (with some tweaks like **making sure "Unredirect FullScreen Windows" option is enabled**) for the XFCE edition.I myself have observed no stablility issues with korrode's package and think that it could be a better solution to the screen tearing issue.For KDE I think just adding this line to MHWDCONFIG could fix the issue of screen tearing with it on Nvidia graphics cards:

```
if [ -f /usr/bin/kwin_x11 ]
then
echo export '__GL_YIELD="USLEEP"' | tee -a /etc/profile.d/FixTearing.sh
fi
```

**Comment by philmmanjaro** [comment]
Well with 71f5b5590dcfae4ce75cc8f4b75724a9b02dcdfa enabled the videos and games work better on my end. Sure everybody can mod their own configs. This is just the one best for almost all cases. Sure it will remove some speed in some games. I think we will add a config modifier gui to MSM to have it more flexible. So everybody can tune his needs.

**Comment by PhoronixSucks** [comment]
> This is just the one best for almost all cases.

That is actually not correct philm as numerous people reported bugs and poor performance with it enabled in some games.At best it seems like a workaround that shouldn't be used at all if there is a better option available.

>Sure it will remove some speed in some games

In my testing it made TF2 unplayable and any game using Wine have excess stuttering.That might not seem like a lot but those two consitutes about 90% of the total games I play.

>I think we will add a config modifier gui to MSM to have it more flexible. So everybody can tune his needs.

That seems like a good option but I in my opinion think that having this disabled by default is the best thing to do at this moment seeing as it has some heavy issues that don't occur when using a proper compositor in it's place.

**Comment by PhoronixSucks** [comment]
@philmmanjaro  Okay now that the commit has been reverted what do you think of my idea of including compiz-manjaro as the default compositing manager instead of XFCE and also that KDE tweak philm? I assessed all available options for removing the screen tearing before coming to those two options respecitively for the two editions of Manjaro.

**Comment by korrode** [comment]
We'd put out a Xfce-Compiz ISO and try to get some broader feedback before considering making it the main edition.

Also Compton (stand-alone compositor, as opposed to Compiz which is a compositing WM) should be considered too.

**Comment by PhoronixSucks** [comment]
>We'd put out a Xfce-Compiz ISO and try to get some broader feedback before considering making it the main edition.

Okay I get it you want to make sure there are no serious bugs with it before rolling it out.A very good thing to do in my opinion as the Compton 0.9 series has been **very unstable** in the past.I also suggest you guys take a look at the Compiz-Reloaded project in case things don't work out well.

>Also Compton (stand-alone compositor, as opposed to Compiz which is a compositing WM) should be considered too.

I have mixed feelings with Compton as even though it is much lighterweight than Compiz it seems to not work as universally as Compiz does but if you feel it is good enough I won't object to it.

**Comment by PhoronixSucks** [comment]
The main purpose of the issue that I created is solved so I'll close this.
